version: "3.8"
services:
  rl-stats:
    container_name: rl-stats-gatherer
    image: ghcr.io/janoz-nl/rl-stats-gatherer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MQTT_HOST=       # MQTT broker host
      - MQTT_SSL=        # Optional, default false
      - MQTT_PORT=       # Optional, default 1883
      - MQTT_USERNAME=   # Optional
      - MQTT_PASSWORD=   # Optional
      - MQTT_CLIENT_ID=  # Optional, default rl_stats_gatherer
      - DB_HOST=         # Database host
      - DB_PORT=         # Optional, default 5432
      - DB_USERNAME=     # Database username
      - DB_PASSWORD=     # Database password
      - DB_NAME=         # Optional, default rlstats
