mp.messaging.incoming.rlapi.connector=smallrye-mqtt
mp.messaging.incoming.rlapi.topic=rlapi2mqtt/updatestate
mp.messaging.incoming.rlapi.client-id=rl_stats_gatherer
#mp.messaging.incoming.rlapi.host=${MQTT_HOST}
#mp.messaging.incoming.rlapi.ssl=${MQTT_SSL}
#mp.messaging.incoming.rlapi.port=${MQTT_PORT}
#mp.messaging.incoming.rlapi.username=${MQTT_USERNAME}
#mp.messaging.incoming.rlapi.password=${MQTT_PASSWORD}

quarkus.datasource.db-kind=postgresql
quarkus.flyway.migrate-at-start=true
