mp.messaging.incoming.rlapi.connector=smallrye-mqtt
mp.messaging.incoming.rlapi.host=robal.nl
mp.messaging.incoming.rlapi.ssl=true
mp.messaging.incoming.rlapi.port=8883
mp.messaging.incoming.rlapi.topic=rlapi2mqtt/#
mp.messaging.incoming.rlapi.username=${MQTT_USERNAME}
mp.messaging.incoming.rlapi.password=${MQTT_PASSWORD}

