CREATE TABLE TEAMS
(
    ID              UUID PRIMARY KEY,
    NAME            VARCHAR(20) NOT NULL,
    PRIMARY_COLOR   VARCHAR(7) NOT NULL,
    SECONDARY_COLOR VARCHAR(7) NOT NULL,
    SCORE           INT NOT NULL DEFAULT 0
);

CREATE TABLE MATCHES
(
    ID           UUID PRIMARY KEY,
    HOME_TEAM_ID UUID REFERENCES TEAMS(ID) NOT NULL,
    AWAY_TEAM_ID UUID REFERENCES TEAMS(ID) NOT NULL,
    FIRST_SEEN   TIMESTAMP NOT NULL
);

CREATE TABLE PLAYERS
(
    ID        UUID PRIMARY KEY,
    ONLINE_ID VARCHAR(127) NOT NULL UNIQUE,
    NAME      VARCHAR(127) NOT NULL

);

CREATE TABLE TEAM_PLAYERS
(
    TEAM_ID   UUID REFERENCES TEAMS(ID) NOT NULL,
    PLAYER_ID UUID REFERENCES PLAYERS(ID) NOT NULL,
    SCORE     INT NOT NULL DEFAULT 0,
    GOALS     INT NOT NULL DEFAULT 0,
    SHOTS     INT NOT NULL DEFAULT 0,
    ASSISTS   INT NOT NULL DEFAULT 0,
    SAVES     INT NOT NULL DEFAULT 0,
    DEMOS     INT NOT NULL DEFAULT 0,

    PRIMARY KEY (TEAM_ID, PLAYER_ID)
);