CREATE TABLE TEAMS
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY_COLOR VARCHAR(7) NOT NULL,
    SECONDARY_COLOR VARCHAR(7) NOT NULL,
    SCORE INT NOT NULL DEFAULT 0
);

CREATE TABLE MATCHES
(
    ID INT PRIMARY KEY,
    MATCH_ID   UUID,
    HOME_TEAM_ID INT REFERENCES TEAMS(ID) NOT NULL,
    AWAY_TEAM_ID INT REFERENCES TEAMS(ID) NOT NULL
);

CREATE TABLE PLAYER
(
    ID INT PRIMARY KEY,
    ONLINE_ID VARCHAR(127) UNIQUE,
    NAME VARCHAR(127)

);

CREATE TABLE TEAM_PLAYER
(
    ID INT PRIMARY KEY,
    TEAM_ID INT REFERENCES TEAMS(ID) NOT NULL,
    PLAYER_ID INT REFERENCES PLAYER(ID) NOT NULL,
    SCORE INT NOT NULL DEFAULT 0,
    GOALS INT NOT NULL DEFAULT 0,
    SHOTS INT NOT NULL DEFAULT 0,
    ASSISTS INT NOT NULL DEFAULT 0,
    SAVES INT NOT NULL DEFAULT 0,
    DEMOS INT NOT NULL DEFAULT 0
);