ALTER TABLE MATCHES ADD CLUB_ID INT;

CREATE TABLE MATCH_URLS
(
    ID       UUID PRIMARY KEY,
    MATCH_ID UUID REFERENCES MATCHES(ID) NOT NULL,
    TYPE     VARCHAR(255) NOT NULL,
    URL      VARCHAR(511) NOT NULL
);
